local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local f = ls.function_node

return {
	s("for", { t("for "), i(1, "i"), t(" in "), i(2, "range(10)"), t({ ":", "    " }), i(3, "pass") }),
	s("while", { t("while "), i(1, "condition"), t({ ":", "    " }), i(2, "pass") }),
	s("def", { t("def "), i(1, "function_name"), t("("), i(2), t({ "):", "    " }), i(3, "pass") }),
	s("class", { t("class "), i(1, "ClassName"), t({ ":", "    def __init__(self):", "        " }), i(2, "pass") }),
	s("try", {
		t({ "try:", "    " }),
		i(1, "pass"),
		t({ "", "except " }),
		i(2, "Exception"),
		t(" as "),
		i(3, "e"),
		t({ ":", "    " }),
		i(4, "print(e)"),
	}),
	s("ife", {
		t("if "),
		i(1, "condition"),
		t({ ":", "    " }),
		i(2, "pass"),
		t({ "", "elif " }),
		i(3, "condition2"),
		t({ ":", "    " }),
		i(4, "pass"),
		t({ "", "else:", "    " }),
		i(5, "pass"),
	}),
	s("listcomp", { t("["), i(1, "x"), t(" for "), i(2, "x in iterable"), t("]") }),
	s("lambda", { t("lambda "), i(1, "x"), t(": "), i(2, "x * 2") }),
	s("with", {
		t("with open("),
		i(1, "'file.txt'"),
		t(", "),
		i(2, "'r'"),
		t(") as "),
		i(3, "f"),
		t({ ":", "    " }),
		i(4, "data = f.read()"),
	}),
	s("main", { t({ 'if __name__ == "__main__":', "    " }), i(1, "main()") }),
	s("imp", { t("import "), i(1, "module") }),
	s("fromimp", { t("from "), i(1, "module"), t(" import "), i(2, "something") }),
	s("doc", { t({ '"""', "" }), i(1, "Description"), t({ "", '"""' }) }),
	s("dictcomp", { t("{"), i(1, "k: v"), t(" for "), i(2, "k, v in iterable"), t("}") }),
	s("enum", {
		t({ "from enum import Enum", "", "class " }),
		i(1, "Color"),
		t("(Enum):"),
		t({ "", "    RED = 1", "    GREEN = 2", "    BLUE = 3" }),
	}),
	s("prop", { t({ "@property", "def " }), i(1, "name"), t("(self):"), t({ "", "    " }), i(2, "return self._name") }),
	s("setcomp", { t("{"), i(1, "x"), t(" for "), i(2, "x in iterable"), t("}") }),
	s("genexp", { t("("), i(1, "x"), t(" for "), i(2, "x in iterable"), t(")") }),
	s("asyncdef", { t("async def "), i(1, "func_name"), t("("), i(2), t({ "):", "    " }), i(3, "await something()") }),
	s("await", { t("await "), i(1, "async_func()") }),
	s("dataclass", {
		t({ "from dataclasses import dataclass", "", "@dataclass", "class " }),
		i(1, "MyClass"),
		t({ ":", "    " }),
		i(2, "field: int"),
	}),
	s("deftyped", {
		t("def "),
		i(1, "func"),
		t("("),
		i(2, "arg: int"),
		t(") -> "),
		i(3, "int"),
		t({ ":", "    " }),
		i(4, "return arg"),
	}),
	s("classtyped", {
		t("class "),
		i(1, "MyClass"),
		t({ ":", "    def __init__(self, " }),
		i(2, "x: int"),
		t("):"),
		t({ "", "        self.x = x", "", "    def __str__(self) -> str:", "        return str(self.x)" }),
	}),
	s("varhint", { i(1, "name"), t(": "), i(2, "str"), t(" = "), i(3, "'value'") }),
	s("typealias", { i(1, "StrList"), t(" = list["), i(2, "str"), t("]") }),
	s("union", { i(1, "value"), t(": "), i(2, "int | None"), t(" = None") }),
}
